/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface AboutController : XXUnknownSuperclass {
	BOOL _firstViewDidAppear;
}
-(id)deviceName:(id)name;
-(void)setDeviceName:(id)name specifier:(id)specifier;
-(void)viewWillDisappear:(BOOL)view;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)viewDidAppear:(BOOL)view;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)willUnlock;
-(id)init;
@end

