/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "EAAccessoryDelegate.h"

@class NSString, EAAccessory;

__attribute__((visibility("hidden")))
@interface AccessoryDetailsController : XXUnknownSuperclass <EAAccessoryDelegate> {
	EAAccessory* _accessory;
	BOOL _shouldEscape;
	BOOL _finishedAppearing;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)accessoryDidDisconnect:(id)accessory;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)_accessoryDidUpdate:(id)_accessory;
-(void)findAppForAccessory;
-(void)disconnect;
-(void)connect;
-(id)bonjourName;
-(id)hardwareRevision;
-(id)firmwareRevision;
-(id)serialNumber;
-(id)modelNumber;
-(id)manufacturer;
-(void)viewDidAppear:(BOOL)view;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

