/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import "AdvertisingController.h"

@class UIView, UITableViewCell;

__attribute__((visibility("hidden")))
@interface AdSupportController : AdvertisingController {
	BOOL _hasRefreshedStatus;
	BOOL _limitAdTrackingURLIsReachable;
	id _restrictionsChangedObserver;
	id _effectiveSettingsChangedObserver;
	UITableViewCell* _limitAdTrackingCell;
	UIView* _originalAccessoryView;
	SCNetworkReachabilityRef _reachability;
}
@property(assign, nonatomic) SCNetworkReachabilityRef reachability;
@property(assign, nonatomic) BOOL limitAdTrackingURLIsReachable;
@property(assign, nonatomic) BOOL hasRefreshedStatus;
@property(retain, nonatomic) UIView* originalAccessoryView;
@property(retain, nonatomic) UITableViewCell* limitAdTrackingCell;
@property(retain, nonatomic) id effectiveSettingsChangedObserver;
@property(retain, nonatomic) id restrictionsChangedObserver;
-(void)dealloc;
-(void)userDidTapLearnMoreLink:(id)user;
-(void)userDidTapDoneButton:(id)user;
-(void)setLimitAdTrackingEnabled:(id)enabled specifier:(id)specifier;
-(id)limitAdTrackingEnabled:(id)enabled;
-(BOOL)canChangeLimitAdTracking;
-(void)resetAdID;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)specifiers;
-(void)viewDidLoad;
@end

