/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AdvertisingController.h"

@class PSSpecifier;

__attribute__((visibility("hidden")))
@interface AdvertisingRestrictionsController : AdvertisingController {
	PSSpecifier* _allowedGroup;
	id _restrictionsChangedObserver;
	id _effectiveSettingsChangedObserver;
}
@property(retain, nonatomic) id effectiveSettingsChangedObserver;
@property(retain, nonatomic) id restrictionsChangedObserver;
-(void)dealloc;
-(id)featureValue:(id)value;
-(void)setFeatureValue:(id)value specifier:(id)specifier;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)specifiers;
@end

