/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface AllowChangesCell : XXUnknownSuperclass {
	UIImageView* _lock;
}
-(void)layoutSubviews;
-(BOOL)canReload;
-(void)setValue:(id)value;
@end

