/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface AutomaticContentDownloadController : XXUnknownSuperclass {
	id _settingsChangedObserver;
	NSMutableArray* _applications;
	NSMutableDictionary* _applicationStates;
}
@property(retain, nonatomic) NSMutableDictionary* applicationStates;
@property(retain, nonatomic) NSMutableArray* applications;
-(id)applicationEnabled:(id)enabled;
-(void)setApplicationEnabled:(id)enabled forSpecifier:(id)specifier;
-(id)backgroundRefreshState:(id)state;
-(void)setBackgroundRefreshState:(id)state withSpecifier:(id)specifier;
-(id)specifiers;
-(id)whitelist;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)dealloc;
-(id)init;
@end

