/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BiometricKitDelegate <NSObject>
@optional
-(void)taskResumeStatus:(long)status;
-(void)templateUpdate:(id)update withDetails:(id)details;
-(void)homeButtonPressed;
-(void)enrollProgress:(id)progress;
-(void)statusMessage:(unsigned)message;
-(void)matchResult:(id)result withDetails:(id)details;
-(void)matchResult:(id)result;
-(void)enrollResult:(id)result;
@end

