/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ControlCenterListController : XXUnknownSuperclass {
}
-(void)setAllowedWithinApps:(id)apps specifier:(id)specifier;
-(id)allowedWithinApps:(id)apps;
-(void)profileNotification:(id)notification;
-(void)setEnabledInLockScreen:(id)lockScreen specifier:(id)specifier;
-(id)enabledInLockScreen:(id)lockScreen;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

