/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SuggestedAppsController;

__attribute__((visibility("hidden")))
@interface ContinuityController : XXUnknownSuperclass {
	SuggestedAppsController* _suggestedAppsController;
}
-(void)setContinuityEnabled:(id)enabled specifier:(id)specifier;
-(id)isContinuityEnabled:(id)enabled;
-(id)specifiers;
-(void)profileNotification:(id)notification;
-(void)updateContinuitySpecifiers;
-(BOOL)isContinuityRestricted;
-(void)dealloc;
-(id)init;
@end

