/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIDatePicker;

__attribute__((visibility("hidden")))
@interface DateTimePickerCell : XXUnknownSuperclass {
	UIDatePicker* _datePicker;
}
-(void)dealloc;
-(void)layoutSubviews;
-(id)datePicker;
-(void)timeZoneChanged:(id)changed;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

