/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIPopoverControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Preferences-Structs.h"

@class NSString, UIPopoverController, PSWallClockMinuteTimer, NSTimer, NSIndexPath, PSSpecifier;

__attribute__((visibility("hidden")))
@interface DateTimeController : XXUnknownSuperclass <UIPopoverControllerDelegate> {
	UIPopoverController* _setDateAndTimePopoverController;
	NSIndexPath* _setDateAndTimeIndexPath;
	NSTimer* _timer;
	BOOL _localeForces24HourTime;
	BOOL _setDateAndTimePopoverShouldRePresent;
	CFDateFormatterRef _dateFormatter;
	CFDateFormatterRef _timeFormatter;
	PSSpecifier* _timeZoneSpecifier;
	PSSpecifier* _timePickerSpecifier;
	PSSpecifier* _currentTimeSpecifier;
	PSWallClockMinuteTimer* _minuteTimer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) PSWallClockMinuteTimer* minuteTimer;
@property(retain) PSSpecifier* currentTimeSpecifier;
@property(retain) PSSpecifier* timePickerSpecifier;
@property(retain) PSSpecifier* timeZoneSpecifier;
-(id)currentDateString;
-(id)currentTimeString;
-(void)_createDateTimeFormatters;
-(void)_updateCurrentTime;
-(void)setTimeZoneValue:(id)value specifier:(id)specifier;
-(id)timeZoneValue:(id)value;
-(void)set24HourTime:(id)time specifier:(id)specifier;
-(id)is24HourTime:(id)time;
-(void)setUseAutomaticTime:(id)time specifier:(id)specifier;
-(id)useAutomaticTime:(id)time;
-(id)valueForTime:(id)time;
-(BOOL)shouldDisplayTimezoneSpinner;
-(void)localeChanged:(id)changed;
-(void)significantTimeChange:(id)change;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)newCarrierNotification;
-(void)viewWillDisappear:(BOOL)view;
-(void)datePickerChanged:(id)changed;
-(BOOL)tableView:(id)view shouldHighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)makeCurrentTimeSpecifier;
-(id)makeTimePickerSpecifier;
-(void)reloadTimezone;
-(void)setAutomaticTimeFooter;
-(id)specifiers;
-(id)init;
-(void)dealloc;
-(void)_setSpecifier:(id)specifier valueEnabled:(BOOL)enabled;
@end

