/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DevicePINControllerDelegate <NSObject>
@optional
-(void)devicePINControllerDidDismissPINPane:(id)devicePINController;
-(void)devicePINController:(id)controller didAcceptChangedPIN:(id)pin;
-(void)devicePINController:(id)controller didAcceptSetPIN:(id)pin;
-(void)didAcceptSetPIN;
-(void)didAcceptRemovePIN;
-(void)didAcceptChangedPIN;
-(void)didCancelEnteringPIN;
-(void)willCancelEnteringPIN;
-(void)didAcceptEnteredPIN:(id)pin;
-(void)didAcceptEnteredPIN;
-(void)willAcceptEnteredPIN;
@end

