/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface DisplayController : XXUnknownSuperclass {
}
-(void)brightnessChangedExternally;
-(void)setBacklightValue:(id)value specifier:(id)specifier;
-(id)backlightValue:(id)value;
-(void)_cleanupTransactionRef;
-(id)boldTextEnabledForSpecifier:(id)specifier;
-(void)setBoldTextEnabled:(id)enabled specifier:(id)specifier;
-(id)controllerForSpecifier:(id)specifier;
-(id)specifiers;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

