/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface FindMyiPhoneController : XXUnknownSuperclass {
	NSObject<OS_dispatch_semaphore>* _stateChangeSem;
}
+(id)shared;
-(void)disablePhoneLocatorWithMessageString:(id)messageString buttonTitle:(id)title completion:(id)completion;
-(void)enablePhoneLocatorWithCompletion:(id)completion;
-(id)preferredFindMyiPhoneAccount;
-(void)locatorStateDidChange:(id)locatorState;
-(BOOL)isFindMyiPhoneEnabled;
-(BOOL)isFindMyiPhoneProvisioned;
-(void)dealloc;
-(id)init;
@end

