/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FMFSessionDelegate <NSObject>
@optional
-(void)didReceiveServerError:(id)error;
-(void)didUpdatePendingOffersForHandles:(id)handles;
-(void)didUpdateActiveDeviceList:(id)list;
-(void)didChangeActiveLocationSharingDevice:(id)device;
-(void)didFailToHandleMappingPacket:(id)handleMappingPacket error:(id)error;
-(void)mappingPacketProcessingCompleted:(id)completed;
-(void)sendMappingPacket:(id)packet toHandle:(id)handle;
-(void)didUpdateHidingStatus:(BOOL)status;
-(void)didStopAbilityToGetLocationForHandle:(id)handle;
-(void)didStartAbilityToGetLocationForHandle:(id)handle;
-(void)didStopSharingMyLocationWithHandle:(id)handle;
-(void)didStartSharingMyLocationWithHandle:(id)handle;
-(void)didReceiveFriendshipRequest:(id)request;
-(void)connectionError:(id)error;
-(void)didFailToFetchLocationForHandle:(id)handle withError:(id)error;
-(void)didReceiveLocation:(id)location;
@end

