/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DevicePINControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "CRCarPlayPreferencesDelegate.h"

@class NSString, NSArray, CRCarPlayPreferences, TVOutManager, NSDictionary, NSTimer, NSMutableDictionary, PSSpecifier;

__attribute__((visibility("hidden")))
@interface GeneralController : XXUnknownSuperclass <CRCarPlayPreferencesDelegate, DevicePINControllerDelegate> {
	NSArray* _autoLockValues;
	NSDictionary* _autoLockTitleDictionary;
	NSMutableDictionary* _localizedAutoLockTitleDictionary;
	NSTimer* _usageTimer;
	TVOutManager* _tvOutManager;
	PSSpecifier* _tvOutSpecifier;
	PSSpecifier* _siriSpecifier;
	CRCarPlayPreferences* _carPreferences;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) CRCarPlayPreferences* carPreferences;
-(void)handleURL:(id)url;
-(BOOL)shouldDeferPushForSpecifierID:(id)specifierID;
-(void)didCancelEnteringPIN;
-(void)didAcceptEnteredPIN:(id)pin;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)_localizeAutoLockTitles;
-(void)enableEdge:(id)edge;
-(id)EDGEEnabled:(id)enabled;
-(id)init;
-(void)profileNotification:(id)notification;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)setLocksAndUnlocksWithCase:(id)aCase specifier:(id)specifier;
-(id)locksAndUnlocksWithCase:(id)aCase;
-(id)parentalControlsEnabled:(id)enabled;
-(void)dealloc;
-(void)handleCarPlayAllowedDidChange;
-(void)updateAssistantSpecifiers;
-(BOOL)_hasCarPlayContent;
-(id)specifiers;
-(void)_setUseSwitchForOrientationLockWithSpecifier:(id)specifier;
-(void)setScreenLock:(id)lock specifier:(id)specifier;
-(id)screenLock:(id)lock;
-(void)handleTVOutChange;
-(void)updateAutoLockSpecifier;
@end

