/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ListRestrictionsController : XXUnknownSuperclass {
}
-(void)reloadAndColor;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)setRowToSelect;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)setValueForSpecifier:(id)specifier defaultValue:(id)value;
-(void)colorCells;
-(id)specifiers;
-(id)allowKey;
-(id)disallowKey;
-(id)mediaKey;
-(id)headerKey;
-(void)dealloc;
-(id)init;
-(id)restrictionsController;
@end

