/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, LocationUsageMixin;

__attribute__((visibility("hidden")))
@interface LocationServicesAuthLevelCell : XXUnknownSuperclass {
	NSURL* _bundleURL;
	BOOL _isWebApp;
	LocationUsageMixin* _location;
	unsigned _authLevel;
}
@property(readonly, assign, nonatomic) unsigned authLevel;
@property(readonly, assign, nonatomic) LocationUsageMixin* location;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(id)getLazyIcon;
-(id)getLazyIconID;
-(BOOL)canReload;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

