/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LocationServicesListController.h"

@class NSString, NSDictionary, NSBundle;

__attribute__((visibility("hidden")))
@interface LocationServicesAuthorizationLevelController : LocationServicesListController {
	NSString* _serviceKey;
	NSDictionary* _details;
	NSString* _displayName;
	NSBundle* _entityBundle;
}
@property(retain, nonatomic) NSBundle* entityBundle;
@property(copy, nonatomic) NSString* displayName;
@property(retain, nonatomic) NSDictionary* details;
@property(copy, nonatomic) NSString* serviceKey;
-(void)_setLocationAuthorizationLevelMaskForAssociatedFramework:(unsigned)associatedFramework;
-(void)_setLocationAuthorizationLevelForSpecifier:(id)specifier;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)_usageTextForAuthorizationLevel:(unsigned)authorizationLevel;
-(id)_purposeStringForAuthorizationLevel:(unsigned)authorizationLevel;
-(id)_constructFooterForAuthorizationLevel:(unsigned)authorizationLevel;
-(id)specifiers;
-(void)dealloc;
-(void)setSpecifier:(id)specifier;
@end

