/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class LocationUsageMixin;

__attribute__((visibility("hidden")))
@interface LocationServicesSubDirectoryCell : XXUnknownSuperclass {
	LocationUsageMixin* _location;
}
@property(readonly, assign, nonatomic) LocationUsageMixin* location;
-(BOOL)canReload;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

