/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class PSTableCell, UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface LocationUsageMixin : XXUnknownSuperclass {
	PSTableCell* _cell;
	int _usage;
	UIImageView* _usageIndicator;
	UILabel* _authLevelLabel;
@private
	BOOL _labelOverlapsIndicator;
@protected
	float horizontalOffset;
	unsigned _authLevel;
}
@property(assign, nonatomic) float horizontalOffset;
@property(assign, nonatomic) unsigned authLevel;
@property(assign, nonatomic) int usage;
-(void)layoutUsageIndicator;
-(id)_authLevelForMask:(unsigned)mask;
-(CGSize)_authLevelLabelSize:(unsigned)size;
-(CGSize)usageIndicatorSize;
-(id)iconNameForUsage:(int)usage;
-(void)dealloc;
-(id)initWithTableCell:(id)tableCell;
@end

