/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FMFSessionDelegate.h"

@class NSString, FMFDevice, UIActionSheet, FMFSession, NSArray, NSOperationQueue, NSMutableArray, ACAccount, NSDictionary, ACAccountStore, NSDate, NSMutableDictionary, NSNumber, UIAlertView;

__attribute__((visibility("hidden")))
@interface LocationServicesListController : XXUnknownSuperclass <FMFSessionDelegate> {
	NSDictionary* _locationEntitiesDetails;
	NSMutableArray* _coalescedSystemServices;
	NSArray* _ignoredLocationEntities;
	UIActionSheet* _locationConfirmationSheet;
	UIAlertView* _locationConfirmationAlert;
	BOOL _locationSwitchedAlertButtons;
	BOOL _deferredRefreshDueToConfirm;
	BOOL _locationNotificationsEnabled;
	BOOL _locationDetailSpecifiersGroupOptional;
	NSMutableDictionary* _coalesceAppKeys;
	NSDate* _twentyFourHoursAgo;
	ACAccountStore* _accountStore;
	ACAccount* _primaryAccount;
	NSOperationQueue* _locationSharingOperationQueue;
	FMFSession* _locationSharingSession;
	FMFDevice* _locationSharingDevice;
	NSNumber* _locationSharingEnabled;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)isLocationRestricted;
+(void)setCoreRoutineAuthorized:(BOOL)authorized;
+(BOOL)isCoreRoutineAuthorized;
-(void)didUpdateHidingStatus:(BOOL)status;
-(void)didChangeActiveLocationSharingDevice:(id)device;
-(void)connectionError:(id)error;
-(void)mainThreadDidUpdateHidingStatus:(BOOL)mainThread;
-(void)mainThreadDidChangeActiveLocationSharingDevice:(id)mainThread;
-(void)mainThreadConnectionError:(id)error;
-(id)locationSharingDevice;
-(BOOL)isLocationSharingEnabled;
-(id)locationSharingSession;
-(id)locationSharingOperationQueue;
-(unsigned long long)locationSharingTimeout;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)specifiers;
-(void)updateLocationSharingSpecifiersWithReload:(BOOL)reload;
-(id)locationSharingSpecifiers;
-(BOOL)isLocationSharingModificationAllowed;
-(BOOL)_shouldEnableLocationSharingSpecifier;
-(id)primaryAccount;
-(id)accountStore;
-(void)_locationSharingSpecifierWasTapped:(id)tapped;
-(id)locationDetailSpecifiers;
-(id)localizedDisplayNameForBundleID:(id)bundleID;
-(id)hiddenBundleIdentifiers;
-(void)showLocationPrivacyPage;
-(void)willBecomeActive;
-(void)viewWillAppear:(BOOL)view;
-(void)updateForApplicationDidBecomeActive:(id)updateForApplication;
-(void)updateRecentlyUsedDate;
-(void)updateMutableStateForLocationSharing;
-(void)updateSpecifiersForImposedSettingsWithReload:(BOOL)reload;
-(void)updateSpecifiersForImposedSettings;
-(void)updateFindMyFriendsStateBasedOnRestriction;
-(void)updateMutableStateBasedOnRestriction;
-(BOOL)isFindMyFriendsModificationAllowed;
-(void)disableAfterLoginConfirmation:(id)confirmation;
-(void)setEntityAuthorized:(id)authorized specifier:(id)specifier;
-(void)_setEntityAuthorized:(BOOL)authorized specifier:(id)specifier;
-(id)isEntityAuthorized:(id)authorized;
-(BOOL)_isFindMyDeviceSpecifier:(id)specifier;
-(void)confirmationClickedButtonAtIndex:(int)index;
-(void)confirmationActionWithSpecifier:(id)specifier;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)_setLocationServicesEnabled:(BOOL)enabled;
-(void)disableLocationServicesAfterConfirm:(id)confirm;
-(void)_cancelConfirmDisableForSpecifier:(id)specifier;
-(void)setLocationServicesEnabled:(id)enabled specifier:(id)specifier;
-(void)refreshLinkStatusInParent;
-(id)isLocationServicesEnabled:(id)enabled;
-(int)locationUsageForEntity:(id)entity;
-(int)locationUsageBasedOnDetails:(id)details;
-(void)stopLocationStatusUpdates;
-(void)startLocationStatusUpdates;
-(void)updateLocationUsage;
-(void)setUsage:(int)usage forCell:(id)cell;
-(void)setAuthLevel:(unsigned)level forCell:(id)cell;
-(void)profileNotification:(id)notification;
-(void)dealloc;
-(id)init;
@end

