/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LocationIndicatorExplanationView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface LocationIndicatorSystemExplanationView : LocationIndicatorExplanationView {
	UILabel* _additionalInfoLabel;
}
-(float)preferredHeightForWidth:(float)width inTableView:(id)tableView;
-(void)layoutForWidth:(float)width inTableView:(id)tableView;
-(void)dealloc;
-(id)initWithSpecifier:(id)specifier;
@end

