/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PSHeaderFooterView.h"

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface LocationIndicatorExplanationView : XXUnknownSuperclass <PSHeaderFooterView> {
	UIImageView* _activeIcon;
	UILabel* _activeLabel;
	UIImageView* _recentIcon;
	UILabel* _recentLabel;
	UIImageView* _geofenceIcon;
	UILabel* _geofenceLabel;
}
-(float)preferredHeightForWidth:(float)width inTableView:(id)tableView;
-(float)preferredHeightForWidth:(float)width;
-(void)layoutSubviews;
-(void)layoutForWidth:(float)width inTableView:(id)tableView;
-(void)dealloc;
-(id)initWithSpecifier:(id)specifier;
@end

