/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TCCAccessController.h"


__attribute__((visibility("hidden")))
@interface MotionFitnessController : TCCAccessController {
}
-(void)setFitnessTrackingEnabled:(id)enabled forSpecifier:(id)specifier;
-(id)isFitnessTrackingEnabled:(id)enabled;
-(BOOL)isFitnessTrackingEnabledFromTCC;
-(id)_appSpecifiers;
-(id)specifiers;
@end

