/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PSHeaderFooterView.h"

@class UIColor, UnderlineButton, UILabel;

__attribute__((visibility("hidden")))
@interface MultitaskingGestureExplanationView : XXUnknownSuperclass <PSHeaderFooterView> {
	UILabel* _labels[4];
	UnderlineButton* _videoLinkButton;
	float _sized;
	float _width;
	UIColor* _footerTextColor;
}
-(id)_accessibilityLabels;
-(void)layoutSubviews;
-(BOOL)isRTL;
-(void)dealloc;
-(float)preferredHeightForWidth:(float)width;
-(id)initWithSpecifier:(id)specifier;
-(id)newRegionSampleLabelUnderlined;
@end

