/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIAlertView;

__attribute__((visibility("hidden")))
@interface MusicRestrictionsController : XXUnknownSuperclass {
	UIAlertView* _iAPAlertView;
}
-(void)dealloc;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)setExplicitEnabled:(id)enabled specifier:(id)specifier;
-(id)explicitEnabled:(id)enabled;
-(id)specifiers;
@end

