/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "URLEditingController.h"

@class WebRestrictionsController;

__attribute__((visibility("hidden")))
@interface NamedURLEditingController : URLEditingController {
	BOOL _saved;
	WebRestrictionsController* _URLSaveController;
}
@property(retain, nonatomic) WebRestrictionsController* URLSaveController;
@property(assign, nonatomic) BOOL saved;
-(id)controlledURL:(id)url;
-(void)setControlledURL:(id)url specifier:(id)specifier;
-(id)controlledURLTitle:(id)title;
-(void)setControlledURLTitle:(id)title specifier:(id)specifier;
-(void)saveURL;
-(void)viewWillDisappear:(BOOL)view;
-(void)willResignActive;
-(void)viewDidAppear:(BOOL)view;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)specifiers;
-(void)dealloc;
@end

