/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DevicePINControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIAlertView, PSSpecifier;

__attribute__((visibility("hidden")))
@interface PasscodeLockController : XXUnknownSuperclass <DevicePINControllerDelegate> {
	int _policyDictatedMaxFailedAttempts;
	PSSpecifier* _voiceDialSpecifier;
	PSSpecifier* _voiceDialGroupSpecifier;
	UIAlertView* _enablePasscodeMesaChoice;
	UIAlertView* _disablePasscodeWarning;
	UIAlertView* _disableSafariPasswordsAlert;
	BOOL _canUnlockWatch;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL canUnlockWatch;
+(int)passcodeGracePeriod;
-(void)viewWillAppear:(BOOL)view;
-(void)profileNotification:(id)notification;
-(void)disablePasscodeRequiredSpecifiers:(id)specifiers;
-(void)setEnabledInLockScreen:(id)lockScreen specifier:(id)specifier;
-(id)enabledInLockScreen:(id)lockScreen;
-(id)specifiers;
-(void)suspend;
-(BOOL)canBeShownFromSuspendedState;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)showKeychainAlert;
-(void)willCancelEnteringPIN;
-(void)didAcceptRemovePIN;
-(void)devicePINController:(id)controller didAcceptChangedPIN:(id)pin;
-(void)willAcceptEnteredPIN;
-(void)_didUpdatePasscode:(id)passcode;
-(void)devicePINController:(id)controller didAcceptSetPIN:(id)pin;
-(id)_makeWipeDeviceGroupFooter;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_setWipeEnabled:(BOOL)enabled;
-(void)setWipeEnabled:(id)enabled specifier:(id)specifier;
-(id)wipeEnabled:(id)enabled;
-(BOOL)showReplyWithMessage;
-(BOOL)isPassbookRestricted;
-(void)setPassbook:(id)passbook specifier:(id)specifier;
-(id)passbook:(id)passbook;
-(BOOL)isAssistantRestricted;
-(void)setAssistantUnderLockEnabled:(id)enabled forSpecifier:(id)specifier;
-(id)assistantUnderLockEnabled:(id)enabled;
-(void)updateVoiceDialGroup;
-(BOOL)isVoiceDialRestricted;
-(BOOL)shouldShowVoiceDial;
-(void)setVoiceDial:(id)dial specifier:(id)specifier;
-(id)voiceDial:(id)dial;
-(void)_localizeGracePeriodTitlesForSpecifier:(id)specifier;
-(void)_updateGracePeriodForSpecifier:(id)specifier;
-(void)updateGracePeriodSpecifier;
-(void)setGraceValue:(id)value specifier:(id)specifier;
-(id)graceValue:(id)value;
-(void)setSimplePasscodeEnabled:(id)enabled specifier:(id)specifier;
-(id)isSimplePasscodeEnabled:(id)enabled;
-(void)togglePasscode:(id)passcode;
-(BOOL)isPasscodeSet;
-(void)dealloc;
-(id)init;
@end

