/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PrefsListController;

__attribute__((visibility("hidden")))
@interface PrefsRootController : XXUnknownSuperclass {
	PrefsListController* _rootListController;
}
+(void)playRingtoneWithIdentifier:(id)identifier loop:(BOOL)loop;
-(void)dealloc;
-(id)initWithTitle:(id)title identifier:(id)identifier;
-(void)loadView;
-(id)rootListController;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(void)setViewControllers:(id)controllers animated:(BOOL)animated;
-(void)setupControllerForToolbar:(id)toolbar;
-(void)mediaServerDiedNotification:(id)notification;
@end

