/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DevicePINControllerDelegate.h"
#import "Preferences-Structs.h"
#import "RadiosPreferencesDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIActionSheetDelegate.h"
#import "PSSearchControllerDelegate.h"

@class NSString, UIActionSheet, NSArray, NSObject, NSDictionary, UIViewController, ACAccountStore, PSSearchController, EAAccessory, NSSet, PSSpecifier;
@protocol PSController, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface PrefsListController : XXUnknownSuperclass <PSSearchControllerDelegate, UIActionSheetDelegate, RadiosPreferencesDelegate, DevicePINControllerDelegate> {
	BOOL _didFirstLoad;
	EAAccessory* _speakerAccessory;
	PSSpecifier* _eqSpecifier;
	NSArray* _thirdPartySpecifiers;
	NSDictionary* _movedThirdPartySpecifiers;
	BOOL _initiallyLoadingThirdPartySpecifiers;
	BOOL _refreshingThirdPartySpecifiers;
	BOOL _victoriaCapable;
	PSSpecifier* _victoriaSpecifier;
	PSSpecifier* _notificationsSpecifier;
	PSSpecifier* _castleSpecifier;
	PSSpecifier* _twitterSpecifier;
	PSSpecifier* _facebookSpecifier;
	PSSpecifier* _flickrSpecifier;
	PSSpecifier* _vimeoSpecifier;
	PSSpecifier* _weiboSpecifier;
	PSSpecifier* _tencentweiboSpecifier;
	PSSpecifier* _messagesSpecifier;
	PSSpecifier* _faceTimeSpecifier;
	PSSpecifier* _gameCenterSpecifier;
	PSSpecifier* _carrierSelectionSpecifier;
	PSSpecifier* _personalHotspotSpecifier;
	BOOL _wifiValueIsClean;
	BOOL _bluetoothValueIsClean;
	NSArray* _originalSpecifiers;
	NSSet* _originalDisplayIdentifiers;
	NSObject<OS_dispatch_queue>* _iconCacheQueue;
	NSDictionary* _iconCache;
	UIActionSheet* _airplaneSheet;
	ACAccountStore* _accountStore;
	BOOL _skipSelectingGeneralOnLaunch;
	PSSearchController* _searchController;
	NSString* _wifiString;
	NSString* _bluetoothString;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* bluetoothString;
@property(copy, nonatomic) NSString* wifiString;
@property(assign, nonatomic) BOOL skipSelectingGeneralOnLaunch;
@property(readonly, retain, nonatomic) PSSearchController* searchController;
@property(readonly, assign, nonatomic) UIViewController<PSController>* categoryController;
+(void)formatSearchEntries:(id)entries parent:(id)parent;
+(void)setAirplaneMode:(BOOL)mode;
+(BOOL)airplaneMode;
+(id)radiosPreferences;
-(id)rootSpecifiersForSearchController:(id)searchController;
-(void)searchController:(id)controller openURL:(id)url;
-(BOOL)shouldDeferPushForSpecifierID:(id)specifierID;
-(void)suspend;
-(void)configurePasscodeSpecifierFromSpecifiers:(id)specifiers;
-(void)didCancelEnteringPIN;
-(void)didAcceptEnteredPIN:(id)pin;
-(void)bluetoothPowerChanged:(id)changed;
-(id)bluetoothValue:(id)value;
-(void)bluetoothValueFetch:(id)fetch;
-(void)iMessageSupportMayHaveChanged;
-(void)lazyLoadSpecialBundleForSpecifier:(id)specifier;
-(id)cellularDataStatusForSpecifier:(id)specifier;
-(void)airplaneModeChanged;
-(id)phoneStatusForSpecifier:(id)specifier;
-(id)cellularDisabledStatusForSpecifier:(id)specifier;
-(void)reloadCellularRelatedSpecifiers;
-(id)getAirplaneMode:(id)mode;
-(void)confirmationSpecifierCancelled:(id)cancelled;
-(void)confirmationSpecifierConfirmed:(id)confirmed;
-(void)_setAirplaneMode:(BOOL)mode;
-(void)setAirplaneMode:(id)mode specifier:(id)specifier;
-(void)_beginObservingAccountStoreDidChangeNotification;
-(id)_accountStore;
-(void)appleAccountsDidChange;
-(void)_setupiCloudSpecifier:(id)specifier;
-(void)setupAppleAccountCategory:(id)category;
-(void)MISStateChangedNotification:(id)notification;
-(void)updatePersonalHotspotWithState:(int)state andReason:(int)reason;
-(id)getTetheringStatus:(id)status;
-(id)wifiNetwork:(id)network;
-(void)wifiNetworkFetch:(id)fetch;
-(void)updateWifi;
-(void)willEnterForeground;
-(void)updateShowsCarrierSettingsMenuVisibility;
-(void)setShowsCarrierSettingsMenu:(BOOL)menu;
-(void)networkChanged;
-(id)currentNetwork:(id)network;
-(void)_localeChanged;
-(void)_newCarrierNotification;
-(void)_simStatusChanged:(CFStringRef)changed;
-(id)specifierForBundle:(id)bundle;
-(id)specifierForID:(id)anId;
-(void)loadPPTTestSpecifiers:(int)specifiers;
-(void)_reallyLoadThirdPartySpecifiersForProxies:(id)proxies withCompletion:(id)completion;
-(void)loadThirdPartySpecifierForBundleID:(id)bundleID;
-(void)_loadThirdPartySpecifiersWithCompletion:(id)completion;
-(void)_loadThirdPartySpecifiersIfNecessaryWithCompletion:(id)completion;
-(id)dndGlobalState:(id)state;
-(BOOL)handlePendingURL;
-(id)specifiers;
-(id)passbookSpecifier;
-(void)traitCollectionDidChange:(id)traitCollection;
-(void)updateWeiboState;
-(void)updateAccountSpecifiers;
-(void)updateRestrictedSettings;
-(void)displayIdentifiersChanged;
-(BOOL)shouldReloadSpecifiersOnResume;
-(void)refresh3rdPartyBundles;
-(void)popToRoot;
-(void)insertMovedThirdPartySpecifiersAtStartIndex:(unsigned)startIndex usingInsertBlock:(id)block andExistenceBlock:(id)block3;
-(id)_specifierDictionaryForDeveloperBundlePath:(id)developerBundlePath identifier:(id)identifier;
-(id)_specifierDictionaryForBundlePath:(id)bundlePath identifier:(id)identifier internalIcon:(BOOL)icon searchPlist:(id)plist;
-(BOOL)_showCarrier;
-(void)_showControllerFromSpecifier:(id)specifier;
-(id)_sidebarSpecifierForCategoryController;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)viewDidAppear:(BOOL)view;
-(id)identifierForSelectedIndex;
-(id)generalViewController;
-(void)selectGeneralCategoryForced:(BOOL)forced showController:(BOOL)controller;
-(void)selectGeneralCategoryForced:(BOOL)forced;
-(void)selectGeneralCategory;
-(void)checkDeveloperSettingsState;
-(void)dealloc;
-(id)init;
-(void)_showDetailTargetDidChange:(id)_showDetailTarget;
-(void)rerootNavigationController;
-(void)viewWillAppear:(BOOL)view;
-(void)reloadSpecifiers;
-(void)clearCache;
-(void)setSpeakerAccessory:(id)accessory eqAvailable:(BOOL)available;
@end

