/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface PSCarrierRejectCodePane : XXUnknownSuperclass {
	UILabel* _rejectMessage;
}
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(void)layoutSubviews;
-(void)setPreferenceSpecifier:(id)specifier;
@end

