/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PSCellularAccountOptionsController : XXUnknownSuperclass {
}
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)selectPlanWithSpecifier:(id)specifier;
-(void)addNewPlanPressed:(id)pressed;
-(void)subscriptionUpdatedNotification;
-(void)carrierChangedNotification;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

