/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PSCellularAccountDetailDelegate.h"
#import "PSSpecifierGroupController.h"

@class NSString, PSListController, CTCellularPlan, PSSpecifier;

__attribute__((visibility("hidden")))
@interface PSCellularAccountGroupController : XXUnknownSuperclass <PSSpecifierGroupController, PSCellularAccountDetailDelegate> {
	PSListController* _listController;
	PSSpecifier* _groupSpecifier;
	CTCellularPlan* _selectedPlan;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) CTCellularPlan* selectedPlan;
@property(assign, nonatomic) PSSpecifier* groupSpecifier;
@property(assign, nonatomic) PSListController* listController;
+(BOOL)shouldShowOtherButton;
+(BOOL)shouldShowAccountSetup;
+(BOOL)isFeatureAvailable;
+(id)getPlanSubscriptionStatus:(int)status;
-(void)dealloc;
-(void)managePlanPressed:(id)pressed;
-(id)getPlanExpireDate:(id)date;
-(id)getPlanPurchaseDate:(id)date;
-(id)getPlanStatusDate:(id)date;
-(id)getPlanStatus:(id)status;
-(id)getCarrierName:(id)name;
-(id)getPlanName:(id)name;
-(id)getSelectedPlan;
-(void)otherButtonPressed:(id)pressed;
-(void)setupAccountPressed:(id)pressed;
-(id)specifiers;
-(BOOL)isSelectedPlanActivating;
-(id)initWithListController:(id)listController groupSpecifier:(id)specifier;
@end

