/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PSCellularAccountDetailDelegate.h"

@class NSString, CTCellularPlan;

__attribute__((visibility("hidden")))
@interface PSCellularAccountDetailsController : XXUnknownSuperclass <PSCellularAccountDetailDelegate> {
	CTCellularPlan* _plan;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) CTCellularPlan* plan;
+(void)configurePlanSpecifiers:(id)specifiers plan:(id)plan target:(id)target selectPlanControllerClass:(Class)aClass;
+(id)specifiersFromCellularPlan:(id)cellularPlan target:(id)target selectPlanControllerClass:(Class)aClass;
-(void)dealloc;
-(void)subscriptionUpdatedNotification;
-(void)managePlanPressed:(id)pressed;
-(id)getPlanExpireDate:(id)date;
-(id)getPlanPurchaseDate:(id)date;
-(id)getPlanStatusDate:(id)date;
-(id)getPlanStatus:(id)status;
-(id)getCarrierName:(id)name;
-(id)getPlanName:(id)name;
-(id)specifiers;
-(id)init;
@end

