/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PSCellularAccountDetailDelegate <NSObject>
@optional
-(void)managePlanPressed:(id)pressed;
-(id)getPlanExpireDate:(id)date;
-(id)getPlanPurchaseDate:(id)date;
-(id)getPlanStatusDate:(id)date;
-(id)getPlanStatus:(id)status;
-(id)getCarrierName:(id)name;
-(id)getPlanName:(id)name;
@end

