/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface PSCellularUsageApp : XXUnknownSuperclass {
	NSString* _bundleIdentifier;
	NSString* _displayName;
	double _totalBytesUsed;
	double _roamingBytesUsed;
}
@property(assign, nonatomic) double roamingBytesUsed;
@property(assign, nonatomic) double totalBytesUsed;
@property(retain, nonatomic) NSString* displayName;
@property(retain, nonatomic) NSString* bundleIdentifier;
-(void)dealloc;
@end

