/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PSStateRestoration.h"


@protocol PSController <PSStateRestoration>
-(void)statusBarWillAnimateByHeight:(float)statusBar;
-(void)willBecomeActive;
-(void)willResignActive;
-(id)readPreferenceValue:(id)value;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(void)handleURL:(id)url;
-(void)showController:(id)controller animate:(BOOL)animate;
-(void)showController:(id)controller;
-(void)didWake;
-(void)didUnlock;
-(void)willUnlock;
-(void)didLock;
-(void)suspend;
-(id)specifier;
-(void)setSpecifier:(id)specifier;
-(id)rootController;
-(void)setRootController:(id)controller;
-(id)parentController;
-(void)setParentController:(id)controller;
@optional
+(id)searchBundle;
+(void)formatSearchEntries:(id)entries parent:(id)parent;
+(void)validateSpecifier:(id)specifier;
-(void)highlightSpecifierWithID:(id)anId;
-(BOOL)prepareHandlingURLForSpecifierID:(id)specifierID resourceDictionary:(id)dictionary animatePush:(BOOL*)push;
-(void)pushController:(id)controller animate:(BOOL)animate;
-(void)pushController:(id)controller;
@end

