/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BiometricKitUIEnrollViewController;

__attribute__((visibility("hidden")))
@interface PSEnrollContainerViewController : XXUnknownSuperclass {
	BiometricKitUIEnrollViewController* _enrollController;
}
@property(retain, nonatomic) BiometricKitUIEnrollViewController* enrollController;
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)viewDidLayoutSubviews;
-(CGRect)frameForEnrollmentController;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)teardown;
-(void)dealloc;
@end

