/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PSFingerprintController : XXUnknownSuperclass {
	id _effectiveSettingsChangedNotificationObserver;
}
@property(retain, nonatomic) id effectiveSettingsChangedNotificationObserver;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)canBeShownFromSuspendedState;
-(BOOL)shouldSelectResponderOnAppearance;
-(id)specifiers;
-(void)setFingerprintName:(id)name;
-(id)fingerprintName;
-(void)deleteFingerprint:(id)fingerprint;
-(id)representedBiometricIdentity;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
@end

