/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PSLeadingCheckmarkCell : XXUnknownSuperclass {
}
+(id)spacerIcon;
+(id)checkIcon;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(void)setChecked:(BOOL)checked;
-(BOOL)canBeChecked;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
@end

