/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface PSLTEOptionsController : XXUnknownSuperclass <UIAlertViewDelegate> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)isOnCallOfSubType:(CFStringRef)subType;
+(void)setVoiceEnabled:(BOOL)enabled;
+(BOOL)shouldShowVoiceOptions;
+(BOOL)isProvisioning;
+(unsigned)voiceAvailability;
+(BOOL)isVoiceEnabled;
+(void)_executeCTConnectionDependentBlock:(id)block;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(BOOL)presentOnCallAlertIfNeededForService:(unsigned)service okayCompletion:(id)completion;
-(void)presentCallCarrierAlert;
-(void)updateProvisioning;
-(void)listItemSelected:(id)selected;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

