/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PSSearchControllerDelegate <NSObject>
-(id)rootSpecifiersForSearchController:(id)searchController;
-(void)searchController:(id)controller openURL:(id)url;
@end

