/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BiometricKitUIEnrollResultDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import "BiometricKitDelegate.h"
#import "PasscodeLockController.h"

@class NSString, UIPopoverController, NSObject, BiometricKit, PSEnrollContainerViewController;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface PSTouchIDPasscodeController : PasscodeLockController <UIPopoverControllerDelegate, BiometricKitUIEnrollResultDelegate, BiometricKitDelegate> {
	BOOL _currentlyEnablingTouchIDForPurchases;
	int _storeState;
	BiometricKit* _highlightMatcher;
	NSObject<OS_dispatch_queue>* _highlightQueue;
	PSEnrollContainerViewController* _enrollController;
	id _modalFlowSuccessCompletion;
	id _modalFlowCancelCompletion;
	UIPopoverController* _enrollmentPopoverController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIPopoverController* enrollmentPopoverController;
@property(assign, nonatomic) BOOL currentlyEnablingTouchIDForPurchases;
@property(copy, nonatomic) id modalFlowCancelCompletion;
@property(copy, nonatomic) id modalFlowSuccessCompletion;
@property(assign, nonatomic) PSEnrollContainerViewController* enrollController;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* highlightQueue;
@property(retain, nonatomic) BiometricKit* highlightMatcher;
@property(assign, nonatomic) int storeState;
+(BOOL)_shouldPresentEnrollmentInPopover;
-(void)didCancelEnteringPIN;
-(void)devicePINController:(id)controller didAcceptSetPIN:(id)pin;
-(void)updateAfterFingerprintChanges;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(id)_fingerprintSpecifierAtIndexPath:(id)indexPath;
-(void)cancelModalFlow;
-(void)completeModalFlow;
-(void)enrollmentCompletedForIdentity:(id)identity;
-(void)hideCancelButton;
-(void)enrollResult:(int)result identity:(id)identity;
-(BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
-(void)_popEnrollmentController;
-(void)presentPasscodePaneFromSpecifier:(id)specifier;
-(void)pushPasscodePane;
-(id)_passcodeControllerForSpecifier:(id)specifier;
-(void)addEnrollment:(id)enrollment;
-(void)_presentPopoverForContentViewController:(id)contentViewController;
-(void)unhighlightFingerprintSpecifiersAfterDelay:(double)delay;
-(void)highlightFingerprintSpecifier:(id)specifier;
-(void)statusMessage:(unsigned)message;
-(void)matchResult:(id)result;
-(void)backgrounded:(id)backgrounded;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)_cancelMatching;
-(void)_setupMatching;
-(id)fingerprintSpecifiers;
-(id)_fingerprintSpecifierForIdentity:(id)identity;
-(id)touchIDSwitchSpecifiers;
-(void)setupTouchIDLogoHeader;
-(void)updateAddFingerprintSpecifier;
-(BOOL)isEnrollmentAvailable;
-(BOOL)shouldRestrictFeaturesRequiringEnrollment;
-(BOOL)isFingerprintEditingAllowed;
-(void)updateTouchIDForStockholmSpecifier;
-(BOOL)isTouchIDForStockholmRestricted;
-(void)setTouchIDForStockholmEnabled:(id)stockholmEnabled specifier:(id)specifier;
-(id)isTouchIDForStockholmEnabled:(id)stockholmEnabled;
-(void)updateTouchIDForPurchasesSpecifier;
-(BOOL)isTouchIDForPurchasesRestricted;
-(void)setTouchIDForPurchasesEnabled:(id)purchasesEnabled specifier:(id)specifier;
-(id)isTouchIDForPurchasesEnabled:(id)purchasesEnabled;
-(id)_authorizationToken;
-(void)updateStoreBiometricsState;
-(void)updateTouchIDUnlockSpecifier;
-(BOOL)isTouchIDUnlockRestricted;
-(void)setTouchIDUnlockEnabled:(id)enabled specifier:(id)specifier;
-(id)isTouchIDUnlockEnabled:(id)enabled;
-(void)addEnrollmentOrCreatePasscodeIfNecessaryWithCompletion:(id)completion;
-(BOOL)hasPasscodeAndFingerprints;
-(id)specifiers;
-(void)didUnlock;
-(void)dealloc;
-(id)init;
@end

