/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer;

__attribute__((visibility("hidden")))
@interface PSWallClockMinuteTimer : XXUnknownSuperclass {
	id _target;
	SEL _action;
	NSTimer* _timer;
}
-(void)_fireAction;
-(void)invalidate;
-(void)startTimer;
-(id)initWithTarget:(id)target selector:(SEL)selector;
@end

