/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface RegulatoryPane : XXUnknownSuperclass {
	UIScrollView* _scrollView;
	UIImageView* _primaryImageView;
	UIImageView* _secondaryImageView;
}
-(void)dealloc;
-(void)viewDidBecomeVisible;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(BOOL)handlesDoneButton;
-(BOOL)shouldInsetContent;
@end

