/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIAlertView, PSSpecifier;

__attribute__((visibility("hidden")))
@interface ResetPrefController : XXUnknownSuperclass {
	BOOL _requireRestrictionsCode;
	BOOL _requirePasscode;
	BOOL _returningFromPINSheetWithSuccess;
	BOOL _shouldEraseWithFMiP;
	BOOL _shouldTryEraseAgainWithFMiP;
	int _codesNeeded;
	int _codesEntered;
	PSSpecifier* _currentSpecifier;
	PSSpecifier* _locationSpecifier;
	int _locationSpecifierIndex;
	NSString* _passcode;
	UIAlertView* _alert;
}
-(void)profileNotification:(id)notification;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)confirmEraseCellularSettings;
-(void)eraseCellularSettings;
-(void)resetAKey;
-(void)reprovisionAccount;
-(void)subscriberOptions:(id)options;
-(id)specifiers;
-(void)resetNetworkSettings:(id)settings;
-(void)eraseSettings:(id)settings;
-(void)_eraseSettingsAndContent;
-(void)locatorStateDidChange:(id)locatorState;
-(void)eraseSettingsAndContent:(id)content;
-(void)_resetWithMode:(int)mode;
-(void)confirmationSpecifierConfirmed:(id)confirmed;
-(void)resetPrivacyWarnings:(id)warnings;
-(void)resetIconPositions:(id)positions;
-(void)resetKeyboardDictionary:(id)dictionary;
-(void)popupViewDidDisappear;
-(void)viewDidAppear:(BOOL)view;
-(void)didAppear;
-(void)didAcceptEnteredPIN:(id)pin;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)updateLocationResetSpecifier;
-(void)dealloc;
-(id)init;
@end

