/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class NSString, NSMutableArray, PSSpecifier, UISwitch, UIAlertView;

__attribute__((visibility("hidden")))
@interface RestrictionsController : XXUnknownSuperclass <UIAlertViewDelegate> {
	UIAlertView* _alert;
	UISwitch* _delayedSwitch;
	BOOL _delayedValue;
	PSSpecifier* _iBooksSpecifier;
	PSSpecifier* _iBooksExplicitSpecifier;
	BOOL _isObservingFaceTimeChanges;
	NSMutableArray* _mcRestrictionFeatures;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* mcRestrictionFeatures;
+(BOOL)requiresPIN;
+(void)formatSearchEntries:(id)entries parent:(id)parent;
-(BOOL)_isSignedInToStore;
-(BOOL)_mesaIsEnabledForStore;
-(id)contentRestriction:(id)restriction;
-(BOOL)canBeShownFromSuspendedState;
-(id)countryCodes;
-(id)currentCountryCode;
-(void)setCountryCode:(id)code reload:(BOOL)reload;
-(id)contentRatingsForMediaType:(id)mediaType;
-(id)iBooksExplicitEnabledString:(id)string;
-(void)setExplicitEnabled:(id)enabled;
-(id)explicitEnabled;
-(id)explicitEnabledString;
-(id)localizedContentRestrictionStringForRank:(id)rank mediaType:(id)type;
-(id)currentCountryString:(id)string;
-(id)specifiers;
-(id)loadSpecifiersFromPlistName:(id)plistName target:(id)target;
-(void)localizedRestrictionSourceDescriptionChanged:(id)changed;
-(void)dealloc;
-(id)init;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)_observeFaceTimeChanges:(BOOL)changes;
-(void)profileNotification:(id)notification;
-(void)_handleExternalApplicationChange;
-(void)updateToggleStateAndReload;
-(void)updateToggleState;
-(void)_setSettingsRestrictedByString;
-(id)_mcRestrictionFeaturesFromSpecifiers:(id)specifiers;
-(void)revertRestrictionPrefsIfNeeded;
-(id)capabilityEnabled:(id)enabled;
-(void)setCapabilityEnabled:(id)enabled specifier:(id)specifier;
-(id)siriContentRestrictionState:(id)state;
-(BOOL)siriContentRestrictionsLockedDown;
-(id)webContentRestrictionState:(id)state;
-(id)featureValue:(id)value;
-(BOOL)featureRestricted:(id)restricted;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)setFeatureValue:(id)value specifier:(id)specifier;
-(void)setReversedBoolFeatureValue:(id)value specifier:(id)specifier;
-(id)reversedBoolFeatureValue:(id)value;
-(void)_handleFaceTimeConferenceStateChanged;
-(void)_disableFaceTimeRestrictions;
-(void)_disableSpecifier:(id)specifier;
-(BOOL)_isInConference;
-(BOOL)_isiTunesUInstalled;
-(BOOL)_isiBooksInstalled;
@end

