/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface RestrictionsPINController : XXUnknownSuperclass {
}
+(void)initialize;
-(BOOL)isNumericPIN;
-(BOOL)simplePIN;
-(CFStringRef)blockedStateKey;
-(CFStringRef)blockTimeIntervalKey;
-(CFStringRef)failedAttemptsKey;
-(CFStringRef)defaultsID;
-(id)pinInstructionsPromptFont;
-(void)performActionAfterPINSet;
-(void)performActionAfterPINRemove;
-(void)delegateUpdateToggleState;
-(BOOL)pinIsAcceptable:(id)acceptable outError:(id*)error;
-(void)setPIN:(id)pin;
-(id)stringsTable;
-(BOOL)validatePIN:(id)pin;
@end

