/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol RUIObjectModelDelegate <NSObject>
-(id)parentViewControllerForObjectModel:(id)objectModel;
@optional
-(void)objectModel:(id)model pressedButton:(id)button attributes:(id)attributes;
-(void)objectModel:(id)model pressedLink:(id)link httpMethod:(id)method;
-(void)objectModelPressedBack:(id)back;
-(Class)objectModel:(id)model customTableCellClassForTableViewRow:(id)tableViewRow;
-(Class)objectModel:(id)model customFooterClassForSection:(id)section;
-(Class)objectModel:(id)model customHeaderClassForSection:(id)section;
-(void)objectModel:(id)model configureTableRow:(id)row page:(id)page;
-(void)objectModel:(id)model configureTableView:(id)view page:(id)page;
-(void)objectModel:(id)model configureTableSection:(id)section page:(id)page;
-(id)objectModel:(id)model tableFooterViewForAttributes:(id)attributes page:(id)page;
-(id)objectModel:(id)model tableHeaderViewForAttributes:(id)attributes page:(id)page;
-(BOOL)objectModel:(id)model page:(id)page deletedTableRow:(id)row atIndexPath:(id)indexPath withURL:(id)url httpMethod:(id)method;
-(BOOL)objectModel:(id)model page:(id)page deletedTableRow:(id)row atIndexPath:(id)indexPath withName:(id)name;
-(unsigned)supportedInterfaceOrientationsForObjectModel:(id)objectModel page:(id)page;
-(void)objectModelDidChange:(id)objectModel;
-(void)objectModel:(id)model page:(id)page toggledEditing:(BOOL)editing;
-(BOOL)objectModel:(id)model shouldShowModalHTMLViewWithURL:(id)url;
-(void)objectModel:(id)model pressedLink:(id)link httpMethod:(id)method completion:(id)completion;
-(void)objectModel:(id)model elementDidChange:(id)element;
-(void)objectModel:(id)model didNavigateBackFromController:(id)controller withGesture:(BOOL)gesture;
-(id)viewControllerForAlertPresentation;
@end

