/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PSCellularAccountGroupController, PSAppCellularUsageGroupController, CHManager, PSListItemsController, PSSpecifier;

__attribute__((visibility("hidden")))
@interface SettingsNetworkController : XXUnknownSuperclass {
	PSSpecifier* _viewAccount;
	PSSpecifier* _viewAccountGroup;
	PSSpecifier* _facetimeSetupButton;
	PSSpecifier* _facetimeSetupGroup;
	BOOL _disabled;
	PSSpecifier* _mobileDataGroup;
	PSSpecifier* _enableRATSpecifier;
	int _RATSwitchKind;
	BOOL _3GOverrideTo4G;
	BOOL _LTEOverrideTo4G;
	PSSpecifier* _currentSpecifier;
	PSSpecifier* _lifetimeSpecifier;
	PSSpecifier* _lastResetSpecifier;
	PSAppCellularUsageGroupController* _appUsageGroupController;
	PSListItemsController* _RATModeDrilldownController;
	BOOL _isOnBootstrap;
	PSCellularAccountGroupController* _cellularGroupController;
	CHManager* _callHistoryManager;
}
@property(assign, nonatomic) BOOL isOnBootstrap;
@property(retain, nonatomic) CHManager* callHistoryManager;
@property(retain, nonatomic) PSCellularAccountGroupController* cellularGroupController;
+(BOOL)isConnectedOverWiFi;
+(BOOL)isOnBootstrapProfile;
-(void)clearStats:(id)stats;
-(void)_updateLastResetText;
-(id)_lastUpdateDate;
-(id)callTime:(id)time;
-(id)lifetimeCallTime:(id)time;
-(id)callTimeDurationRestrictedToCurrentPeriod:(BOOL)currentPeriod;
-(id)totalRoamingDataUsageForSpecifier:(id)specifier;
-(id)totalDataUsageForSpecifier:(id)specifier;
-(id)dataUsageWorkspaceInfo;
-(void)cellularPlanChanged;
-(void)airplaneModeChanged;
-(void)airplaneModeOrSIMStatusChanged;
-(BOOL)isCellularDisabled;
-(void)dataRegistrationChangedWithUserInfo:(id)userInfo;
-(void)handleCallTimersChanged;
-(void)newCarrierNotification;
-(void)totalBytesUsedChangedNotification;
-(void)setupCellularFaceTime:(id)time;
-(BOOL)shouldShowFaceTimeSetup;
-(void)viewAccountPressed:(id)pressed;
-(BOOL)shouldShowViewAccount;
-(BOOL)shouldShowCellularAccountSetup;
-(id)getCDMARoamingStatus:(id)status;
-(void)setCDMARoamingEnabled:(id)enabled specifier:(id)specifier;
-(void)setEUInternetEnabled:(id)enabled specifier:(id)specifier;
-(void)setEUInternetEnabledConfirmed:(id)confirmed;
-(void)setEUInternetCancelled:(id)cancelled;
-(id)getEUInternetStatus:(id)status;
-(void)setDataRoamingEnabled:(id)enabled specifier:(id)specifier;
-(id)getDataRoamingStatus:(id)status;
-(id)roamingSettingsDescription:(id)description;
-(BOOL)showDataPlanOnly;
-(void)reloadRATStatus:(id)status;
-(void)updateRATSpecifiers;
-(BOOL)_updateMobileDataGroupContentShowingRAT:(BOOL)rat;
-(void)updateRATStateWithDictionary:(id)dictionary;
-(id)getRATSwitchIsOn:(id)on;
-(id)getRATModeState:(id)state;
-(BOOL)_setRATModeConfirmed:(int)confirmed;
-(void)_setRATModeStateIsOn:(BOOL)on;
-(void)acceptedRATSwitch:(id)aSwitch;
-(void)canceledRATSwitch:(id)aSwitch;
-(void)setRATSwitchIsOn:(id)on specifier:(id)specifier;
-(void)setRATModeState:(id)state specifier:(id)specifier;
-(id)getLTEService:(id)service;
-(void)setLTEService:(id)service specifier:(id)specifier;
-(BOOL)shouldShowLegacyRATOptions;
-(BOOL)shouldShowLTEOptions;
-(BOOL)supportsVoLTE;
-(id)localizableRATModeStringKeyForKey:(id)key targetMode:(int)mode;
-(id)isMobileDataEnabled:(id)enabled;
-(void)updateAppUsageGroupEnabledState;
-(void)updatePaneWithCellularDataState:(BOOL)cellularDataState;
-(void)_setMobileDataSwitch:(BOOL)aSwitch;
-(void)canceledDataSwitch:(id)aSwitch;
-(void)acceptedDataSwitch:(id)aSwitch;
-(void)setMobileDataIsEnabled:(id)enabled specifier:(id)specifier;
-(void)viewDidAppear:(BOOL)view;
-(id)controllerForSpecifier:(id)specifier;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

