/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PSSpecifier;

__attribute__((visibility("hidden")))
@interface SettingsNetworkRoamingController : XXUnknownSuperclass {
	PSSpecifier* _voiceRoamingSpecifier;
	PSSpecifier* _dataRoamingSpecifier;
	PSSpecifier* _cdmaRoamingSpecifier;
}
-(id)getCDMARoamingStatus:(id)status;
-(void)setCDMARoamingEnabled:(id)enabled specifier:(id)specifier;
-(void)setEUInternetEnabled:(id)enabled specifier:(id)specifier;
-(void)setDataRoamingEnabled:(id)enabled specifier:(id)specifier;
-(id)getEUInternetStatus:(id)status;
-(id)getDataRoamingStatus:(id)status;
-(id)getVoiceRoamingStatus:(id)status;
-(void)setVoiceRoamingEnabled:(id)enabled specifier:(id)specifier;
-(void)reloadRoamingStatus;
-(void)newCarrierNotification;
-(id)specifiers;
-(id)_voiceRoamingFooterTextWithVoiceRoamingOn:(BOOL)voiceRoamingOn;
-(id)cdmaRoamingSpecifiers;
-(id)dataRoamingSpecifiers;
-(void)dealloc;
-(id)init;
@end

