/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SiriContentRestrictionsController : XXUnknownSuperclass {
}
-(id)featureValue:(id)value;
-(void)setFeatureValue:(id)value specifier:(id)specifier;
-(id)reversedBoolFeatureValue:(id)value;
-(void)setReversedBoolFeatureValue:(id)value specifier:(id)specifier;
-(id)specifiers;
@end

