/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SpeakersPrefController : XXUnknownSuperclass {
}
+(BOOL)isVisible;
-(id)eqIndex:(id)index;
-(void)setEQIndex:(id)index specifier:(id)specifier;
-(id)specifiers;
-(void)dealloc;
-(id)init;
-(void)update;
@end

