/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, HMHomeManager;

__attribute__((visibility("hidden")))
@interface TCCAccessController : XXUnknownSuperclass {
	CFStringRef _serviceKey;
	BOOL _iCloudURLIsReachable;
	NSString* _footer;
	NSString* _header;
	NSString* _explanation;
	HMHomeManager* _homeManager;
	SCNetworkReachabilityRef _reachability;
}
@property(assign, nonatomic) BOOL iCloudURLIsReachable;
@property(assign, nonatomic) SCNetworkReachabilityRef reachability;
@property(retain, nonatomic) HMHomeManager* homeManager;
@property(copy, nonatomic) NSString* explanation;
@property(copy, nonatomic) NSString* header;
@property(copy, nonatomic) NSString* footer;
+(BOOL)isServiceRestricted:(id)restricted;
-(void)updateSpecifiersForImposedSettings;
-(void)_resetWillowData;
-(void)_confirmResetWillowData;
-(id)accesssForSpecifier:(id)specifier;
-(void)setAccess:(id)access forSpecifier:(id)specifier;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)specifiers;
-(void)setSpecifier:(id)specifier;
-(void)dealloc;
-(id)init;
@end

