/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ALCity;

__attribute__((visibility("hidden")))
@interface TimeZoneTableCell : XXUnknownSuperclass {
	ALCity* _city;
}
@property(retain, nonatomic) ALCity* city;
-(id)_contentString;
-(void)dealloc;
@end

