/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Preferences-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class TVOutManager;

__attribute__((visibility("hidden")))
@interface TVOutController : XXUnknownSuperclass {
	TVOutManager* _tvOutManager;
}
-(void)setTVSignal:(id)signal specifier:(id)specifier;
-(id)tvSignal:(id)signal;
-(void)setWidescreen:(id)widescreen specifier:(id)specifier;
-(id)isWidescreen:(id)widescreen;
-(void)writeValue:(CFStringRef)value forKey:(CFStringRef)key;
-(void)handleTVOutChange;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end

