/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface URLEditingController : XXUnknownSuperclass {
}
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)canBeShownFromSuspendedState;
-(BOOL)shouldSelectResponderOnAppearance;
-(void)viewWillDisappear:(BOOL)view;
-(void)suspend;
-(id)specifiers;
@end

