/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (ContainsString)
-(BOOL)containsString:(id)string;
@end

@interface XXUnknownSuperclass (DeviceSpecific)
+(id)deviceSpecificImageNamed:(id)named;
@end

@interface XXUnknownSuperclass (PrefsFormatting)
-(id)IMEIString;
-(id)ICCIDString;
@end

@interface XXUnknownSuperclass (ThirdPartyApplicationAdditions)
-(int)_compareBundleDictionary:(id)dictionary;
@end

